import type { Metadata } from "next";
import {  Geist_Mono  } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";

const myFont = localFont({
  src: '../public/fonts/AtlasGrotesk-Medium.otf',
  weight: '300',
  variable: "--font-my-font"
})

const geistSans = myFont;

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
